#!/usr/bin/env bash
# transfers a file to my server
if [ '$#' -lt 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    sed -i '$ a \   StrictHostKeyChecking no' /etc/ssh/ssh_config
    scp -i $4 $1 $3@$2:~/
fi