#!/usr/bin/env bash
# redirects
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i '/^\sserver_name.*/a \        rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default 
sudo service nginx start
